export const HIDE_REMINDER = "HIDE_REMINDER";
export const REMOVE_REMINDER = "REMOVE_REMINDER";
export const SAVE_REMINDER = "SAVE_REMINDER";
export const SAVE_REMINDER_SUCCESS = "SAVE_REMINDER_SUCCESS";
export const SHOW_REMINDER = "SHOW_REMINDER";
